### PR TITLE
Add typings

### LINKED ISSUE #26: Simplify reactify(target)
From https://github.com/sencha/extjs-reactor/issues/12#issuecomment-264384809

I don't like `reactify(...targets)`. I would suggest to keep it simple and do `reactify(target)`.

The consumer does not gain much from doing this "shortcut". It is better to keep it simple. Also, `reactify(...targets)` makes it hard to type and use in TypeScript in the future,when `react` `Property` and `State` can pass down to ExtJS component. 
It also makes the code impossible to use generics.

```ts
import React = require('react')  // You should do this too, CommonJS <-> ESM interop is flawed.
import { reactify } from '@extjs/reactor'

interface GridProperty {}
interface GridState {}
interface GridInterface { }
interface PanelProperty {}
interface PanelState {}
interface PanelInterface { }

const Grid1 = reactify('grid') as GridInterface & React.Component<GridProperty, GridState>

const [ Grid2, Panel ] = reactify('grid', 'panel') as [
  GridInterface & React.Component<GridProperty, GridState>,
  PanelInterface & React.Component<PanelProperty, PanelState>
]

// If using generic, which is what I'm doing:
const Grid3 = reactify<GridInterface, GridProperty, GridState>('grid')
```

I'm using Intersection type `GridInterface & React.Component<...>` because this would allow the consumer to extend the default grid and provide their own property and state.

### PR DESCRIPTION
**Pull request by unional**
Closes #26

### CODE REVIEW

**Comment by unional** [comment]
You can see https://github.com/unional/extjs-reactor/blob/2458278cd05856fd0606c9fd91d7703b9faaa3f3/packages/reactor/src/test/typings.test.ts for use cases

**Comment by unional** [comment]
To simplify commit history, you can use Squash and merge. It's in the setting

**Comment by unional** [comment]
I typically disable merge commit:
image

**Comment by unional** [comment]
Are you ready to merge this? Currently `reactor-typescript-boilerplate` has a copy of this typings and it is working fine. 🌷

**Comment by markbrocato** [comment]
Yes, I plan to review it tomorrow.  Got caught up in VSCode stuff the last few days.  You'll be happy to know that the GA version will only create a .sencha directory when the project contains an Ext JS app :) as you suggested. We received your CLA, so we should be ready to go.

**Comment by unional** [comment]
Nice! 🌷

**Pull request merged**
