### PR TITLE
Error occurred in routing when using tab panel

### PR DESCRIPTION
**Pull request by kazamage**
Use extjs 6.5.2(classic) and react-router v4

Corresponds to an event that an error occurs in component unmounting when tab panel is used.

Uncaught TypeError: Cannot set property '_extIndexInParent' of null

### CODE REVIEW

**Comment by kazamage** [comment]
Apparently continuation of licensing extjs seems to be a risk.

**Comment by BugiDev** [comment]
@dbuhrman Can you please merge this and release a new version? :)

I am getting the same error and this fixes it.
It happens when the element is already destroyed and that is why it can't find *this.el*.

**Comment by BugiDev** [comment]
Hello @mgusmano 
Sorry to bother you but I have seen that you have been doing some work on this project and have the rights to merge and release new version.

Can I please ask you to merge this and release a new version?
I have seen the comment that this will not be needed for the React 16 so it will not break anything you are working on. :)

P.S. Thank you so much for updating the library :) Can't wait to use React 16 in my project.

**Comment by mgusmano** [comment]
can you provide me with a simple example that reproduces the problem?

**Comment by BugiDev** [comment]
@mgusmano I can't create you a reproducible demo, since my use case is fairly complex, but after debugging, I found out that on this line: https://github.com/kazamage/extjs-reactor/blob/a332005153402d32bf9fd85c7f3c19aae30a816c/packages/reactor/src/ExtJSComponent.js#L171

the *el* element is null, and after looking at the component, the flag *destroyed* is set to true, meaning that, for some reason, the lib tries to unmount already destroyed component.

What I am doing is, when I receive some response from the server, I use *ReactDom.render* to create a new page, that creates ExtJS reactified components in a div where the old page used to live.

Now, this might be the problem, but I am not sure, since the *ReactDom.* is responsible for unmounting components.
My use case is similar to the react router from @kazamage (react router does the same thing for routes).

**Comment by mgusmano** [comment]
I added this to the reactor15 package in the  2.0.x-dev branch - this is the branch for v2 of ExtReact

**Pull request closed without merging**
